### ISSUE TITLE
Can this library be used to convert MIDI files into mp3 or wave files?

### ISSUE THREAD

**Issue by Nefcanto** [tebjan/Sanford.Multimedia.Midi#11]
Hi,

Through Google search, I found this library and after downloading I realized that it's a very cool library. Yet I can't find this functionality that I want, to convert MIDI files into mp3 or wave files. 

Can this library be used for that purpose?

**Comment by tebjan** [comment]
hi @nefcanto,

this library might be the building block of your task. i loads midi data and can parse it. what you do with the midi data is up to you. since midi is only note information and not sound, the key element will be a sound generator that takes the midi data and plays instruments with the note data. so your chain will be:

read midi data -> play midi data -> synthesize sound from midi notes -> record sound -> save sound file

the first two steps can be taken by this library. the last two maybe by NAudio? then you will only need a general midi player/synthesizer to generate the sound samples.

**Comment by tebjan** [comment]
since there seems to be no more questions i will close this.
